# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # === Default Branch ===
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - v4
    schedule:
      interval: weekly

  # === Release Branch: v3 ===
  - package-ecosystem: github-actions
    directory: /
    target-branch: release/3
    labels:
      - dependabot
      - v3
    schedule:
      interval: weekly

  # === Release Branch: v2 ===
  - package-ecosystem: github-actions
    directory: /
    target-branch: release/2
    labels:
      - dependabot
      - v2
    schedule:
      interval: weekly

  # === Release Branch: v1 ===
  - package-ecosystem: github-actions
    directory: /
    target-branch: release/1
    labels:
      - dependabot
      - v1
    schedule:
      interval: weekly
